#!/usr/bin/env bash
set -e

TARGET_DIR="${1:-.}"
PROJECT_TYPE="${YWAI_PROJECT_TYPE:-generic}"
EXT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$EXT_DIR/../../.." && pwd)"
SKILLS_SETUP="$REPO_ROOT/skills/setup.sh"

if [[ ! -f "$SKILLS_SETUP" ]]; then
  echo "Global agents installer not found: $SKILLS_SETUP"
  exit 1
fi

# Global user-profile agents are generated by the canonical setup flow.
# This keeps logic data-driven via extensions/templates/bundles.json.
bash "$SKILLS_SETUP" --global-only --project-type="$PROJECT_TYPE" --opencode --copilot

echo "Global agents configured for project type: $PROJECT_TYPE"
